[profile.default]
src = "src"
libs = ["dependencies"]
solc = "0.8.30"
evm_version = "prague"
optimizer = true
optimizer_runs = 4294967295
via_ir = true

[dependencies]
forge-std = "1.10.0"
"@openzeppelin-contracts" = "5.2.0"
sxt-proof-of-sql = { version = "0.123.10", url = "https://github.com/spaceandtimefdn/sxt-proof-of-sql/releases/download/v0.123.10/posql-generated.zip" }
